apiVersion: v1
kind: Pod
metadata:
  name: doblecontenedor
spec:
  containers:
  - name: python1
    image: python:3.6-alpine
    command: ["/bin/sh"]
    args: ["-c", "echo cont1> index.html && python -m http.server 8081"]
  - name: python2
    image: python:3.6-alpine
    command: ["/bin/sh"]
    args: ["-c", "echo cont2 > index.html && python -m http.server 8082"]