apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-prueba
  labels:
    app: front
spec:
  replicas: 3
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - name: webserver
        image: nginx:alpine