apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-nodeport
  labels:
    app: prometheus
spec:
  replicas: 3
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus 
      annotations:
         prometheus.io/scrape: "true"
         prometheus.io/port: "9090"
    spec:
      containers:
      - name: webserver
        image: supergiantkir/prometheus-test-app
---
apiVersion: v1
kind: Service
metadata:
  name: servidores-web
  labels: 
    app: prometheus
spec:
  type: NodePort

  selector:
    app: prometheus
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8081